### ISSUE TITLE
希望增加播放本地SVGA的方法

### ISSUE THREAD

**Issue by zijinzhiyun** [yyued/SVGAPlayer-Android#400]
希望可以增加播放sdcard、内部存储空间的SVGA的方法

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Android/wiki/APIs#parseinputstream-inputstream-cachekey-string-callback-parsecompletion-closeinputstream-boolean--false

**Comment by zijinzhiyun** [comment]
@PonyCui 能否单独提供干净的加载本地SVGA的方法。decodeFromInputStream()提供的加载本地SVGA的方法内部还包含文件的缓存逻辑，这样本地的SVGA文件会在cache目录下再缓存一份。同时库本身提供的缓存是放在内部存储空间的缓存文件目录，这个目录当设备的内部存储空间不足时，Android 可能会删除这些缓存文件以回收空间。这样从网络缓存的SVGA还是会被删除，造成多次从网络下载。

**Comment by PonyCui** [comment]
@zijinzhiyun 2.0 格式文件不会被缓存

**Comment by zijinzhiyun** [comment]
@PonyCui SvgaCache 类型为 FILE不就会缓存了吗

**Comment by zijinzhiyun** [comment]
@PonyCui SVGACache 类型设置为 FILE，直接加载本地的SVGA就会再缓存一遍
